#!/bin/sh

[[ -f ~/.config/X11/xresources ]] && xrdb -load ~/.config/X11/xresources
setxkbmap -layout de
setxkbmap -option caps:escape
xwallpaper --focus bilder/wallpaper/wall.jpg
xcompmgr &
sxhkd &

# Start dwm
exec startdwm
