#!/bin/sh

vsc() { du -a ~/.scripts | awk '{ print $2 }' | fzf | xargs sh -c 'vim "$@" < /dev/tty' vim; }
vco() { du -a ~/.config  | awk '{ print $2 }' | fzf | xargs sh -c 'vim "$@" < /dev/tty' vim; }

