#!/bin/sh

# $1 : Filename

filePath=$1
filename=$(echo $filePath | sed 's/^.*\///; s/\..*$//')
fileExtention=$(echo $filePath | sed 's/.*\.//')


case "$fileExtention" in 
	"rmd")
			# Check the output format
			format=$(grep "output: " $filePath | awk '{print $2}')

			if [ $format = 'pdf_document' ]; then
				pdf=$(echo $filePath | sed 's/.rmd/.pdf/')
				if [ -f $pdf ]; then
					zathura $pdf &
				else
					echo "Datei noch nicht kompelliert"
				fi
			else
				echo "\n--------------------------------"
				echo "Output format nicht bekannt!!!!!"
				echo "--------------------------------"
			fi
			;;
	*)
		echo "\n--------------------------------"
		echo "Datei Endung nicht bekannt!!!!!"
		echo "--------------------------------"
		

esac
