#!/bin/bash
mode=$(echo -e "Bildschirme\nBeamer\nLaptop" | dmenu -i -fn "System San Francisco Display")

#Screen mode
if [ "$mode" = "" ]; then
		exit 1
elif [ "$mode" = "Bildschirme" ]; then
		xrandr --output LVDS1 --off
		xrandr --output HDMI1 --auto
		xrandr --output VGA1 --mode 1600x900 --left-of HDMI1
elif [ "$mode" = "Beamer" ]; then
		xrandr --output LVDS1 --off
		xrandr --output VGA1 --off
		xrandr --output HDMI1 --mode 1024x768
		xrandr --output VGA1 --mode 1024x768 
elif [ "$mode" = "Laptop" ]; then
		xrandr --output HDMI1 --off
		xrandr --output VGA1s --off
		xrandr --output LVDS1 --auto
fi

feh --bg-scale /home/fynn/bilder/wallpaper/wall.jpg
i3 restart
